
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const CHANGE_TAB = 'CHANGE_TAB';

export const UPDATE_AUTH = 'UPDATE_AUTH';

export const UPDATE_USERLIST = 'UPDATE_USERLIST';
export const UPDATE_FRIENDSLIST = 'UPDATE_FRIENDSLIST';
export const UPDATE_FRIENDSINFO = 'UPDATE_FRIENDSINFO';
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';